### ISSUE TITLE
Hello i needed some help 

### ISSUE THREAD

**Issue by shawn3308** [BenjaminCreem/ArduinoLifi#1]
Hello i needed some help

**Comment by pavan2108** [comment]
hello @shawn3308 can you clearly state what kind of help you need so you can get your queries addressed as soon as they can

**Comment by shawn3308** [comment]
Do we have to put something on the SD card and then it transfer it

**Comment by pavan2108** [comment]
yes I know

**Comment by shawn3308** [comment]
No lol I am ask

**Comment by shawn3308** [comment]
I am new to this

**Comment by pavan2108** [comment]
can we connect in discord pavan#8786 I am not clear on what you are saying

**Comment by shawn3308** [comment]
Sure man that would be great
